[package]
name = "three"
version = "0.1.0"
authors = ["Joey Bomber <joseph.bomber@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutohedron = "0.2.4"
termion = "1.5.2"
